## CLASSIFICATION OF IRIS CLASSES USING A NAIVE-BAYES CLASSIFICATION

DATASET SOURCE: "UCI MACHINE LEARNING REPOSITRY" 

### IMPORTING THE LIBRARIES 

In [16]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

In [17]:
dataset=pd.read_csv("iris.csv")
dataset.columns=['sepal length','sepal width','petal length','petal width','Class']

In [18]:
dataset.sample(10)

sepal length  sepal width  petal length  petal width            Class
146           6.5          3.0           5.2          2.0   Iris-virginica
93            5.6          2.7           4.2          1.3  Iris-versicolor
66            5.8          2.7           4.1          1.0  Iris-versicolor
42            5.0          3.5           1.6          0.6      Iris-setosa
112           5.7          2.5           5.0          2.0   Iris-virginica
49            7.0          3.2           4.7          1.4  Iris-versicolor
94            5.7          3.0           4.2          1.2  Iris-versicolor
123           6.7          3.3           5.7          2.1   Iris-virginica
111           6.8          3.0           5.5          2.1   Iris-virginica
45            5.1          3.8           1.6          0.2      Iris-setosa

In [19]:
dataset.shape

(149, 5)

In [20]:
dataset.columns

Index(['sepal length', 'sepal width', 'petal length', 'petal width', 'Class'], dtype='object')

In [21]:
dataset.isna().sum()

sepal length    0
sepal width     0
petal length    0
petal width     0
Class           0
dtype: int64

### 'class' IS THE DEPENDENT VARIABLE 

In [22]:
print(dataset.Class.unique())

['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']


##  Checking the datatypes of the attributes

In [23]:
for i in dataset.columns:
    print(i,"----dtype -------",dataset[i].dtype)

sepal length ----dtype ------- float64
sepal width ----dtype ------- float64
petal length ----dtype ------- float64
petal width ----dtype ------- float64
Class ----dtype ------- object


### SPLITTING INTO DEPENDENT AND INDEPENDENT VARIABLES

In [24]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 4].values

# Splitting the dataset into the Training set and Test set

In [25]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.40, random_state = 42)

## MODEL CREATION AND TRAINING WITH TRAINING SET

In [26]:
from sklearn.naive_bayes import GaussianNB
cls=GaussianNB()
cls.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [27]:
# Predicting the Test set results
y_pred = cls.predict(X_test)

## Confusion Matrix

In [28]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [29]:
print(cm)

[[23  0  0]
 [ 0 14  5]
 [ 0  1 17]]


## ACCURACY

In [30]:
print("ACCURACY OF MODEL IS : ",cls.score(X_test,y_test)*100,"%")

ACCURACY OF MODEL IS :  90.0 %


## WE HAVE CREATED A MODEL THAT CAN CLASSIFY THE IRIS DATA INTO THEIR RESPECTIVE CLASS  WITH AN ACUURACY OF 90.0 %